language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarqube:
    token:
      secure: "ie4jg2Lspu0kgKJZuaW4jBlqwp9xCGoof0tyh7fMSu5eYPhImZcqTj6FS80wadKIuN3RK54jNwYe5hU1zrSe8wNZuaOLPXoaNpXJviN2LhxEpGsWyxE4lUSgVaSW49fQd9E6tO1nut6V9mSk4BiAFDoh7N+ovc83LQ0lbme2fXmi1FM1UotAUsYu6NRBLy2UKPuAjdsMGRVMnRse+1/BeVEnYBWyTl3p11wY+rsB2rOfB4veMOQmil0ADo7Bm9q81NqevnueYN9TbPAFjtjpUTNXZanL3GgBYaYGxy0/fu85tLVXC2LufJWIA47WQ++qO5Z+Rhz4V18PfRVlPGgiWJwUMF+iBPcTKYglIbjd75TMmqIGVOJInB0AJ+Pi9uYqCsCJIkJ1aPG9sbh4e+mc3KmSKMNjXo7O7vam2sj7gYF5msWclEf3lEz9JCwjA9TEZmelBLtJEPvGPhDy1rfzgesb33bRvm3SSRl2R+owdm6yr7ee/7aYpyZ/y+MzVMYQldEEhEvaHmJ582LnPiUdKLtYVpReBwAQbdWnlGuaUhcjnoroGeH+J4rdMD1LZzcl9+UlM3nP+BPjNbOHZyfcZ8ynz5RGTH6l7g3fya9h7vbynABlTmoz2mI9riTbGAoAp2Bf07Dtiedpx4JoYt4QkfJHpI0etwevXe1XIE0mhf4="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
