language: java

addons:
  sonarqube:
    token:
      secure: MilmUiDu0fMlSmIFBrmvNKVMf51Z22MM9pU7LUTEb9YkzHvNAttLiGCl3xL1ex8urEKMjr8uTddbPCwCJNhyhWnQ/xKVUz9yGU1uVntBF0wE9CoY433qlOHlG9epEGPfgbQZ9D29vY0zjX9hWyiWAEn4RrKNe2q2HD6hfHsbHBSO1JehdshzP814aq7fmJdwdcDLvSVIc7/SGRfm4gpOqPGkc49QAlQYiovWKDpIGZ770iTZ5xWdafLK7yAK+2t9vSnMoXJ8MVfcfz67R4KfWwms57ENOboByA7Dz8toRBuNYW/ILxs+rmAOBOAKarBWCPYdX2O0ZXJRhqf0dTiQUS+V6CSAIZq8yXzmB9r5GSxmBZxleu0hdwaKXPuElC7porOxn4Hq4ebkHdE7FFYPmdsGHreFtEBRa1e+RFqaqIFIQsLjjscfw86mwr+GueGljD9CU+7195HBqSC2+8+cHXFQ7YdxprtOesgoCFLOdIGBhYOJb40QeZDYKN9gHhY6OHIKAch6nhkxelQm01+ufGqZXBd2QkLCVJ/456LwN5tOrkEiz9wrsH861qDjQqjMHNQb8O+S1BUHr3MS4ctAGSMVBS8YUR5Z/70oRzElE6npDkhNGm6jUoRsJjDSrekF319tq/xn6vnCtezy1Qqlli7CMFLKO79mqg9ttQUU5OI= # encrypted value of your token
    github_token:
      secure: IOQHorDW8zSe3sCfbeWyg62lpS+Bu6/X/E2nWeS5q3mNc2hktXulSJ2aq8b1wQqCLFZuO3SIaG0gO+SGr+epUpFDvS4X07mOm8wFfJQ36DRWZt8G1/Xao3ugid91MRWb49UssgId9D3Cd9ESM/JcsKn7uWYYcPxWU8BSLk0RFYfEqyyqO693BrzlyzhQhi9rneqssqwMNpARo5PgEGRKGnk8zBsYXPH5DRSbnecBb5atzCZmoLvA6TNYAsy2iJ+XPo4R8px8E06QDmN7cceHnneJszHJ+uOZ7MvI6gEKHYrUsM5EzljXOYc2Axex2Sd5C1bCSNA02H3NDW2KWSb4P4qoQIH7XAkYHn6FecrS3ILmL0TSTdIvNtS4B0JV9Ib+qF03BXd3OjMeNP5KhSvg5kJKCCNw0lkXtv7zNQa+59Molo7g9AjNNYUhZu5vETc0iOukrkOwTYbqxOxFRHs1vdS3OzATnCPWKHRhvIYmld/oGjYv+V0HRXy0gAr6Lb1kULG5RqFjrskLLE944eIFe+dNTy8zTg9ataWjDubHeOIdlVTuob45VQ40HkGgh3MT1N7R0q8cIizBfjYndMLRaZ5Aw3Zmf5xjeknxQmOgzWruDmPnC68Hbwz3qkC2/esRRKwVf4qvrv4SyNywPdo7bsUjilPKrHqlfkilVSnqC48=

  branches:
    - .*

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
